### ISSUE TITLE
404 page not appearing, being replaced by default GH Pages one

### ISSUE THREAD

**Issue by matfantinel** [matfantinel/matfantinel.github.io#13]
This seems to be caused by the lack of a 404.html file since I'm using a generic error page, on __error.svelte

**Comment by KaminariOS** [comment]
Yeah. I hope Svelte static adapter team will fix this in the future.

**Comment by matfantinel** [comment]
@felixsanz thanks! I missed that on the docs. Seems other few things have changed (like named layouts). Gonna apply this as soon as I have time.

**Comment by matfantinel** [comment]
On #26, I cloned the __error.svelte and used the build script to manually add it to the root of the generated folder as 404.html. This way, GitHub Pages displayed that file instead of its generic one.
