### ISSUE TITLE
Licensing Usage

### ISSUE THREAD

**Issue by jsmenzies** [matfantinel/matfantinel.github.io#17]
Hi Matt,

Forgive me for opening an issue but I couldn't DM you on twitter.

I've just started learning Svelte/kit and came across your site. Really blown away by how smooth and good looking it is. I see your licensing is GPL, does this mean I am able to fork and modify the content to serve as my own site, with credits to you?

Just wanted to check before I started, thanks!

**Comment by matfantinel** [comment]
Hi James! Thank you for the kind words! 

Yes, the GPL license requires that every use of the code is distributed under a compatible license (basically it should be open source as well) but I of course won't enforce it, but consider doing it so your code helps other people as well!

No need to credit me but feel free to do so if you like!

**Comment by jsmenzies** [comment]
Thank you, I really appreciate it and will make sure to add credit anyway since you deserve it!

For someone beginning learning Svelte/frontend dev your site is like the golden standard!
