### ISSUE TITLE
Implement container queries

### ISSUE THREAD

**Issue by matfantinel** [matfantinel/matfantinel.github.io#42]
[Container queries](https://fantinel.dev/container-queries) will be really great for the Card component since it currently looks a bit weird, since `flex-wrap` is tough to get right.

They're now supported in all browsers, however https://github.com/sveltejs/svelte/issues/6969 is currently a blocker.

**Comment by xKesvaL** [comment]
Dunno if you've looked into it since then, but it looks fixed as of today!

**Comment by matfantinel** [comment]
@xKesvaL Awesome! Now the only blocker is my (lack of) free time 😄
